config/routes.rb
PgHero::Engine.routes.draw do
  scope "(:database)", constraints: proc { |req| (PgHero.config["databases"].keys + [nil]).include?(req.params[:database]) } do
    get "cluster_info", to: "home#cluster_info"
    get "data_distribution", to:"home#data_distribution"
    get "landlord", to:"home#landlord"
    get "citus_settings", to:"home#citus_settings"
    get "space", to: "home#space"
    get "space/:relation", to: "home#relation_space", as: :relation_space
    get "index_bloat", to: "home#index_bloat"
    get "live_queries", to: "home#live_queries"
    get "queries", to: "home#queries"
    get "queries/:query_hash", to: "home#show_query", as: :show_query
    get "system", to: "home#system"
    get "cpu_usage", to: "home#cpu_usage"
    get "connection_stats", to: "home#connection_stats"
    get "replication_lag_stats", to: "home#replication_lag_stats"
    get "load_stats", to: "home#load_stats"
    get "free_space_stats", to: "home#free_space_stats"
    get "explain", to: "home#explain"
    get "tune", to: "home#tune"
    get "connections", to: "home#connections"
    get "maintenance", to: "home#maintenance"
    post "kill", to: "home#kill"
    post "kill_long_running_queries", to: "home#kill_long_running_queries"
    post "kill_all", to: "home#kill_all"
    post "enable_query_stats", to: "home#enable_query_stats"
    post "explain", to: "home#explain"
    post "reset_query_stats", to: "home#reset_query_stats"
    post "reset_landlord_stats", to: "home#reset_landlord_stats"

    # legacy routes
    get "system_stats" => redirect("system")
    get "query_stats" => redirect("queries")

    root to: "home#index"
  end
end

app/controllers/pg_hero/home_controller.rb
module PgHero
  class HomeController < ActionController::Base
    layout "pg_hero/application"

    protect_from_forgery

    http_basic_authenticate_with name: ENV["PGHERO_USERNAME"], password: ENV["PGHERO_PASSWORD"] if ENV["PGHERO_PASSWORD"]

    if respond_to?(:before_action)
      before_action :check_api
      before_action :set_database
      before_action :set_query_stats_enabled
      before_action :set_show_details, only: [:index, :queries, :show_query]
      before_action :ensure_query_stats, only: [:queries]
    else
      # no need to check API in earlier versions
      before_filter :set_database
      before_filter :set_query_stats_enabled
      before_filter :set_show_details, only: [:index, :queries, :show_query]
      before_filter :ensure_query_stats, only: [:queries]
    end

    def index
      @title = "Overview"
      @extended = params[:extended]
      @citus_enabled = @database.citus_enabled?

      if @replica
        @replication_lag = @database.replication_lag
        @good_replication_lag = @replication_lag ? @replication_lag < 5 : true
      else
        @inactive_replication_slots = @database.replication_slots.select { |r| !r[:active] }
      end

      @autovacuum_queries, @long_running_queries = @database.long_running_queries.partition { |q| q[:query].starts_with?("autovacuum:") }

      @total_connections = @database.total_connections
      @good_total_connections = @total_connections < @database.total_connections_threshold

      @transaction_id_danger = @database.transaction_id_danger(threshold: 1500000000)

      @readable_sequences, @unreadable_sequences = @database.sequences.partition { |s| s[:readable] }

      @sequence_danger = @database.sequence_danger(threshold: (params[:sequence_threshold] || 0.9).to_f, sequences: @readable_sequences)

      @indexes = @database.indexes
      @invalid_indexes = @indexes.select { |i| !i[:valid] }
      @duplicate_indexes = @database.duplicate_indexes(indexes: @indexes)

      if @query_stats_enabled
        @query_stats = @database.query_stats(historical: true, start_at: 3.hours.ago)
        @slow_queries = @database.slow_queries(query_stats: @query_stats)
        set_suggested_indexes((params[:min_average_time] || 20).to_f, (params[:min_calls] || 50).to_i)
      else
        @query_stats_available = @database.query_stats_available?
        @query_stats_extension_enabled = @database.query_stats_extension_enabled? if @query_stats_available
        @suggested_indexes = []
      end

      if @extended
        @index_hit_rate = @database.index_hit_rate || 0
        @table_hit_rate = @database.table_hit_rate || 0
        @good_cache_rate = @table_hit_rate >= @database.cache_hit_rate_threshold / 100.0 && @index_hit_rate >= @database.cache_hit_rate_threshold / 100.0
        @unused_indexes = @database.unused_indexes(max_scans: 0)
      end

      @show_migrations = PgHero.show_migrations
    end

    def cluster_info
      @title = "Cluster Info"
      @citus_enabled = @database.citus_enabled?
      @citus_version = @database.citus_version
      @nodes_info = @database.nodes_info
      @dist_tables_extended = @database.dist_tables_extended
      case params[:sort]
      when "name"
        @nodes_info.sort_by! { |n| n[:name] }
      when "size"
        @nodes_info.sort_by! { |n| n[:size] }.reverse!
      when "dist_table_name"
        @dist_tables_extended.sort_by! {|p| p[:dist_table_name]}
      when "part_size"
        @dist_tables_extended.sort_by! {|p| p[:part_size]}.reverse!
      end
    end

    def data_distribution
      @title = "Data Distribution"
      @citus_enabled = @database.citus_enabled?
      @distributed_tables = @database.distributed_tables
      @distributed_tables.each do |distributed_table|
        distributed_table[:shards] = @database.shard_data_distribution(distributed_table[:logicalrelid], distributed_table[:partition_column])
      end
      @colocated_shard_sizes = @database.colocated_shard_sizes
      case params[:sort]
      when "colocated_shards_size"
        @colocated_shard_sizes.sort_by! { |c| c[:colocated_shards_size] }.reverse!
      end
    end

    def landlord
      @title = "Landlord"
      @citus_enabled = @database.citus_enabled?
      @landlord_available = @database.landlord_available?
      if !@query_stats_enabled
        @query_stats_available = @database.query_stats_available?
        @query_stats_extension_enabled = @database.query_stats_extension_enabled? if @query_stats_available
      end
      if @landlord_available
        @landlord_stats = @database.landlord_stats
        case params[:sort]
        when "executor"
          @landlord_stats.sort_by! { |l| l[:executor] }
        when "partition_key"
          @landlord_stats.sort_by! { |l| l[:partition_key] }.reverse!
        end
        @grouped_dist_queries_executor = group_dist_queries(@landlord_stats, :executor)
        @grouped_dist_queries_partkey = (group_dist_queries(@landlord_stats, :partition_key)).to_h.reject { |pk| pk == "-" }.to_a.first(20)
      end
    end

    def citus_settings
      @title = "Settings"
      @citus_enabled = @database.citus_enabled?
      @citus_settings = @database.citus_settings
    end

    def space
      @title = "Space"
      @citus_enabled = @database.citus_enabled?
      @days = (params[:days] || 7).to_i
      @database_size = @database.database_size
      @relation_sizes = params[:tables] ? @database.table_sizes : @database.relation_sizes
      @space_stats_enabled = @database.space_stats_enabled? && !params[:tables]
      if @space_stats_enabled
        space_growth = @database.space_growth(days: @days, relation_sizes: @relation_sizes)
        @growth_bytes_by_relation = Hash[ space_growth.map { |r| [[r[:schema], r[:relation]], r[:growth_bytes]] } ]
        case params[:sort]
        when "growth"
          @relation_sizes.sort_by! { |r| s = @growth_bytes_by_relation[[r[:schema], r[:relation]]]; [s ? 0 : 1, -s.to_i, r[:schema], r[:relation]] }
        when "name"
          @relation_sizes.sort_by! { |r| r[:relation] || r[:table] }
        end
      end

      across = params[:across].to_s.split(",")
      @unused_indexes = @database.unused_indexes(max_scans: 0, across: across)
      @unused_index_names = Set.new(@unused_indexes.map { |r| r[:index] })
      @show_migrations = PgHero.show_migrations
      @system_stats_enabled = @database.system_stats_enabled?
      @index_bloat = [] # @database.index_bloat
      if @citus_enabled
        @node_sizes = @database.node_sizes
      end
    end

    def relation_space
      @schema = params[:schema] || "public"
      @relation = params[:relation]
      @title = @relation
      relation_space_stats = @database.relation_space_stats(@relation, schema: @schema)
      @chart_data = [{name: "Value", data: relation_space_stats.map { |r| [r[:captured_at], (r[:size_bytes].to_f / 1.megabyte).round(1)] }, library: chart_library_options}]
    end

    def index_bloat
      @title = "Index Bloat"
      @index_bloat = @database.index_bloat
      @show_sql = params[:sql]
    end

    def live_queries
      @title = "Live Queries"
      @citus_enabled = @database.citus_enabled?
      @running_queries = @database.running_queries(all: true)
      @vacuum_progress = @database.vacuum_progress.index_by { |q| q[:pid] }
    end

    def queries
      @title = "Queries"
      @citus_enabled = @database.citus_enabled?
      @sort = %w(average_time calls).include?(params[:sort]) ? params[:sort] : nil
      @min_average_time = params[:min_average_time] ? params[:min_average_time].to_i : nil
      @min_calls = params[:min_calls] ? params[:min_calls].to_i : nil

      if @historical_query_stats_enabled
        begin
          @start_at = params[:start_at] ? Time.zone.parse(params[:start_at]) : 24.hours.ago
          @end_at = Time.zone.parse(params[:end_at]) if params[:end_at]
        rescue
          @error = true
        end
      end

      @query_stats =
        if @historical_query_stats_enabled && !request.xhr?
          []
        else
          @database.query_stats(
            historical: true,
            start_at: @start_at,
            end_at: @end_at,
            sort: @sort,
            min_average_time: @min_average_time,
            min_calls: @min_calls
          )
        end

      @indexes = @database.indexes
      set_suggested_indexes

      # fix back button issue with caching
      response.headers["Cache-Control"] = "must-revalidate, no-store, no-cache, private"
      if request.xhr?
        render layout: false, partial: "queries_table", locals: {queries: @query_stats, xhr: true}
      end
    end

    def show_query
      @query_hash = params[:query_hash].to_i
      @user = params[:user].to_s
      @title = @query_hash

      stats = @database.query_stats(historical: true, query_hash: @query_hash, start_at: 24.hours.ago).find { |qs| qs[:user] == @user }
      if stats
        @query = stats[:query]
        @explainable_query = stats[:explainable_query]

        if @show_details
          query_hash_stats = @database.query_hash_stats(@query_hash, user: @user)

          @chart_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at], (r[:total_minutes] * 60 * 1000).round] }, library: chart_library_options}]
          @chart2_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at], r[:average_time].round(1)] }, library: chart_library_options}]
          @chart3_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at], r[:calls]] }, library: chart_library_options}]

          @origins = Hash[query_hash_stats.group_by { |r| r[:origin].to_s }.map { |k, v| [k, v.size] }]
          @total_count = query_hash_stats.size
        end

        @tables = PgQuery.parse(@query).tables rescue []
        @tables.sort!

        if @tables.any?
          @row_counts = Hash[@database.table_stats(table: @tables).map { |i| [i[:table], i[:estimated_rows]] }]

app/helpers/pg_hero/base_helper.rb
module PgHero
  module BaseHelper
    def pghero_pretty_ident(table, schema: nil)
      ident = table
      if schema && schema != "public"
        ident = "#{schema}.#{table}"
      end
      if ident =~ /\A[a-z0-9_]+\z/
        ident
      else
        @database.quote_ident(ident)
      end
    end
  end
end

app/views/layouts/pg_hero/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= [@databases.size > 1 ? @database.name : "PgHero", @title].compact.join(" / ") %></title>

    <meta charset="utf-8" />
    <%= favicon_link_tag "pghero/favicon.png" %>
    <%= stylesheet_link_tag "pghero/application" %>
    <%= javascript_include_tag "pghero/application" %>
  </head>
  <body>
    <div class="container">
      <div class="alert alert-<%= alert ? "danger" : "info" %>">
        <% if alert %>
          <%= alert %>
        <% elsif notice %>
          <%= notice %>
        <% elsif Rails.env.development? %>
          Do not use development information to make decisions about your production environment
        <% else %>
          <%= link_to "PgHero", root_path %>
        <% end %>
      </div>

      <div class="grid">
        <div class="col-3-12">
          <% if @databases.size > 1 %>
            <p class="nav-header"><%= @database.name %></p>
          <% end %>

          <ul class="nav">
            <!-- poor man's active_link_to -->
            <li class="<%= controller.action_name == "index" ? "active" : "" %>"><%= link_to "Overview", root_path %></li>
            <% if @citus_enabled %>
              <li><a href="#" onclick="var x = document.getElementById('citus'); if (x.style.display === 'none') { x.style.display = 'block'; } else { x.style.display = 'none';} this.textContent = this.textContent == 'Citus &#9662;' ? 'Citus &#9663;' : 'Citus &#9662;';">Citus &#9662;</a></li>
              <div id = "citus" style = "display: none; background-color: #fff;">
                <li class="<%= controller.action_name == "cluster_info" ? "active" : "" %>"><%= link_to "Cluster Info", cluster_info_path %></li>
                <li class="<%= controller.action_name == "data_distribution" ? "active" : "" %>"><%= link_to "Data Distribution", data_distribution_path %></li>
                <li class="<%= controller.action_name == "landlord" ? "active" : "" %>"><%= link_to "Landlord", landlord_path %></li>
                <li class="<%= controller.action_name == "citus_settings" ? "active" : "" %>"><%= link_to "Configuration", citus_settings_path %></li>
              </div>
            <% end %>
            <% if @system_stats_enabled %>
              <li class="<%= controller.action_name == "system" ? "active" : "" %>"><%= link_to "System", system_path %></li>
            <% end %>
            <% if @query_stats_enabled %>
              <li class="<%= controller.action_name == "queries" ? "active" : "" %>"><%= link_to "Queries", queries_path %></li>
            <% end %>
            <li class="<%= controller.action_name == "space" ? "active" : "" %>"><%= link_to "Space", space_path %></li>
            <li class="<%= controller.action_name == "connections" ? "active" : "" %>"><%= link_to "Connections", connections_path %></li>
            <li class="<%= controller.action_name == "live_queries" ? "active" : "" %>"><%= link_to "Live Queries", live_queries_path %></li>
            <% unless @database.replica? %>
              <li class="<%= controller.action_name == "maintenance" ? "active" : "" %>"><%= link_to "Maintenance", maintenance_path %></li>
            <% end %>
            <li class="<%= controller.action_name == "explain" ? "active" : "" %>"><%= link_to "Explain", explain_path %></li>
            <li class="<%= controller.action_name == "tune" ? "active" : "" %>"><%= link_to "Tune", tune_path %></li>
          </ul>

          <% if @databases.size > 1 %>
            <p class="nav-header">Databases</p>
            <ul class="nav">
              <% @databases.each do |database| %>
                <li class="<%= ("active-database" if @database.id == database.id) %>">
                  <%= link_to database.name, action_name == "show_query" ? root_path(database: database.id) : {database: database.id} %>
                </li>
              <% end %>
            </ul>
          <% end %>
        </div>

        <div class="col-9-12">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>