config/routes.rb
PgHero::Engine.routes.draw do
  scope "(:database)", constraints: proc { |req| (PgHero.config["databases"].keys + [nil]).include?(req.params[:database]) } do
    get "cluster_info", to: "home#cluster_info"
    get "data_distribution", to:"home#data_distribution"
    get "landlord", to:"home#landlord"
    get "citus_settings", to:"home#citus_settings"
    get "space", to: "home#space"
    get "space/:relation", to: "home#relation_space", as: :relation_space
    get "index_bloat", to: "home#index_bloat"
    get "live_queries", to: "home#live_queries"
    get "queries", to: "home#queries"
    get "queries/:query_hash", to: "home#show_query", as: :show_query
    get "system", to: "home#system"
    get "cpu_usage", to: "home#cpu_usage"
    get "connection_stats", to: "home#connection_stats"
    get "replication_lag_stats", to: "home#replication_lag_stats"
    get "load_stats", to: "home#load_stats"
    get "free_space_stats", to: "home#free_space_stats"
    get "explain", to: "home#explain"
    get "tune", to: "home#tune"
    get "connections", to: "home#connections"
    get "maintenance", to: "home#maintenance"
    post "kill", to: "home#kill"
    post "kill_long_running_queries", to: "home#kill_long_running_queries"
    post "kill_all", to: "home#kill_all"
    post "enable_query_stats", to: "home#enable_query_stats"
    post "explain", to: "home#explain"
    post "reset_query_stats", to: "home#reset_query_stats"
    post "reset_landlord_stats", to: "home#reset_landlord_stats"

    # legacy routes
    get "system_stats" => redirect("system")
    get "query_stats" => redirect("queries")

    root to: "home#index"
  end
end

app/controllers/pg_hero/home_controller.rb
module PgHero
  class HomeController < ActionController::Base
    layout "pg_hero/application"

    protect_from_forgery

    http_basic_authenticate_with name: ENV["PGHERO_USERNAME"], password: ENV["PGHERO_PASSWORD"] if ENV["PGHERO_PASSWORD"]

    if respond_to?(:before_action)
      before_action :check_api
      before_action :set_database
      before_action :set_query_stats_enabled
      before_action :set_show_details, only: [:index, :queries, :show_query]
      before_action :ensure_query_stats, only: [:queries]
    else
      # no need to check API in earlier versions
      before_filter :set_database
      before_filter :set_query_stats_enabled
      before_filter :set_show_details, only: [:index, :queries, :show_query]
      before_filter :ensure_query_stats, only: [:queries]
    end

    def index
      @title = "Overview"
      @extended = params[:extended]
      @citus_enabled = @database.citus_enabled?

      if @replica
        @replication_lag = @database.replication_lag
        @good_replication_lag = @replication_lag ? @replication_lag < 5 : true
      else
        @inactive_replication_slots = @database.replication_slots.select { |r| !r[:active] }
      end

      @autovacuum_queries, @long_running_queries = @database.long_running_queries.partition { |q| q[:query].starts_with?("autovacuum:") }

      @total_connections = @database.total_connections
      @good_total_connections = @total_connections < @database.total_connections_threshold

      @transaction_id_danger = @database.transaction_id_danger(threshold: 1500000000)

      @readable_sequences, @unreadable_sequences = @database.sequences.partition { |s| s[:readable] }

      @sequence_danger = @database.sequence_danger(threshold: (params[:sequence_threshold] || 0.9).to_f, sequences: @readable_sequences)

      @indexes = @database.indexes
      @invalid_indexes = @indexes.select { |i| !i[:valid] }
      @duplicate_indexes = @database.duplicate_indexes(indexes: @indexes)

      if @query_stats_enabled
        @query_stats = @database.query_stats(historical: true, start_at: 3.hours.ago)
        @slow_queries = @database.slow_queries(query_stats: @query_stats)
        set_suggested_indexes((params[:min_average_time] || 20).to_f, (params[:min_calls] || 50).to_i)
      else
        @query_stats_available = @database.query_stats_available?
        @query_stats_extension_enabled = @database.query_stats_extension_enabled? if @query_stats_available
        @suggested_indexes = []
      end

      if @extended
        @index_hit_rate = @database.index_hit_rate || 0
        @table_hit_rate = @database.table_hit_rate || 0
        @good_cache_rate = @table_hit_rate >= @database.cache_hit_rate_threshold / 100.0 && @index_hit_rate >= @database.cache_hit_rate_threshold / 100.0
        @unused_indexes = @database.unused_indexes(max_scans: 0)
      end

      @show_migrations = PgHero.show_migrations
    end

    def cluster_info
      @title = "Cluster Info"
      @citus_enabled = @database.citus_enabled?
      @citus_version = @database.citus_version
      @nodes_info = @database.nodes_info
      @dist_tables_extended = @database.dist_tables_extended
      case params[:sort]
      when "name"
        @nodes_info.sort_by! { |n| n[:name] }
      when "size"
        @nodes_info.sort_by! { |n| n[:size] }.reverse!
      when "dist_table_name"
        @dist_tables_extended.sort_by! {|p| p[:dist_table_name]}
      when "part_size"
        @dist_tables_extended.sort_by! {|p| p[:part_size]}.reverse!
      end
    end

    def data_distribution
      @title = "Data Distribution"
      @citus_enabled = @database.citus_enabled?
      @distributed_tables = @database.distributed_tables
      @distributed_tables.each do |distributed_table|
        distributed_table[:shards] = @database.shard_data_distribution(distributed_table[:logicalrelid], distributed_table[:partition_column])
      end
      @colocated_shard_sizes = @database.colocated_shard_sizes
      case params[:sort]
      when "colocated_shards_size"
        @colocated_shard_sizes.sort_by! { |c| c[:colocated_shards_size] }.reverse!
      end
    end

    def landlord
      @title = "Landlord"
      @citus_enabled = @database.citus_enabled?
      @landlord_available = @database.landlord_available?
      if !@query_stats_enabled
        @query_stats_available = @database.query_stats_available?
        @query_stats_extension_enabled = @database.query_stats_extension_enabled? if @query_stats_available
      end
      if @landlord_available
        @landlord_stats = @database.landlord_stats
        case params[:sort]
        when "executor"
          @landlord_stats.sort_by! { |l| l[:executor] }
        when "partition_key"
          @landlord_stats.sort_by! { |l| l[:partition_key] }.reverse!
        end
        @grouped_dist_queries_executor = group_dist_queries(@landlord_stats, :executor)
        @grouped_dist_queries_partkey = (group_dist_queries(@landlord_stats, :partition_key)).to_h.reject { |pk| pk == "-" }.to_a.first(20)
      end
    end

    def citus_settings
      @title = "Settings"
      @citus_enabled = @database.citus_enabled?
      @citus_settings = @database.citus_settings
    end

    def space
      @title = "Space"
      @citus_enabled = @database.citus_enabled?
      @days = (params[:days] || 7).to_i
      @database_size = @database.database_size
      @relation_sizes = params[:tables] ? @database.table_sizes : @database.relation_sizes
      @space_stats_enabled = @database.space_stats_enabled? && !params[:tables]
      if @space_stats_enabled
        space_growth = @database.space_growth(days: @days, relation_sizes: @relation_sizes)
        @growth_bytes_by_relation = Hash[ space_growth.map { |r| [[r[:schema], r[:relation]], r[:growth_bytes]] } ]
        case params[:sort]
        when "growth"
          @relation_sizes.sort_by! { |r| s = @growth_bytes_by_relation[[r[:schema], r[:relation]]]; [s ? 0 : 1, -s.to_i, r[:schema], r[:relation]] }
        when "name"
          @relation_sizes.sort_by! { |r| r[:relation] || r[:table] }
        end
      end

      across = params[:across].to_s.split(",")
      @unused_indexes = @database.unused_indexes(max_scans: 0, across: across)
      @unused_index_names = Set.new(@unused_indexes.map { |r| r[:index] })
      @show_migrations = PgHero.show_migrations
      @system_stats_enabled = @database.system_stats_enabled?
      @index_bloat = [] # @database.index_bloat
      if @citus_enabled
        @node_sizes = @database.node_sizes
      end
    end

    def relation_space
      @schema = params[:schema] || "public"
      @relation = params[:relation]
      @title = @relation
      relation_space_stats = @database.relation_space_stats(@relation, schema: @schema)
      @chart_data = [{name: "Value", data: relation_space_stats.map { |r| [r[:captured_at], (r[:size_bytes].to_f / 1.megabyte).round(1)] }, library: chart_library_options}]
    end

    def index_bloat
      @title = "Index Bloat"
      @index_bloat = @database.index_bloat
      @show_sql = params[:sql]
    end

    def live_queries
      @title = "Live Queries"
      @citus_enabled = @database.citus_enabled?
      @running_queries = @database.running_queries(all: true)
      @vacuum_progress = @database.vacuum_progress.index_by { |q| q[:pid] }
    end

    def queries
      @title = "Queries"
      @citus_enabled = @database.citus_enabled?
      @sort = %w(average_time calls).include?(params[:sort]) ? params[:sort] : nil
      @min_average_time = params[:min_average_time] ? params[:min_average_time].to_i : nil
      @min_calls = params[:min_calls] ? params[:min_calls].to_i : nil

      if @historical_query_stats_enabled
        begin
          @start_at = params[:start_at] ? Time.zone.parse(params[:start_at]) : 24.hours.ago
          @end_at = Time.zone.parse(params[:end_at]) if params[:end_at]
        rescue
          @error = true
        end
      end

      @query_stats =
        if @historical_query_stats_enabled && !request.xhr?
          []
        else
          @database.query_stats(
            historical: true,
            start_at: @start_at,
            end_at: @end_at,
            sort: @sort,
            min_average_time: @min_average_time,
            min_calls: @min_calls
          )
        end

      @indexes = @database.indexes
      set_suggested_indexes

      # fix back button issue with caching
      response.headers["Cache-Control"] = "must-revalidate, no-store, no-cache, private"
      if request.xhr?
        render layout: false, partial: "queries_table", locals: {queries: @query_stats, xhr: true}
      end
    end

    def show_query
      @query_hash = params[:query_hash].to_i
      @user = params[:user].to_s
      @title = @query_hash

      stats = @database.query_stats(historical: true, query_hash: @query_hash, start_at: 24.hours.ago).find { |qs| qs[:user] == @user }
      if stats
        @query = stats[:query]
        @explainable_query = stats[:explainable_query]

        if @show_details
          query_hash_stats = @database.query_hash_stats(@query_hash, user: @user)

          @chart_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at], (r[:total_minutes] * 60 * 1000).round] }, library: chart_library_options}]
          @chart2_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at], r[:average_time].round(1)] }, library: chart_library_options}]
          @chart3_data = [{name: "Value", data: query_hash_stats.map { |r| [r[:captured_at], r[:calls]] }, library: chart_library_options}]

          @origins = Hash[query_hash_stats.group_by { |r| r[:origin].to_s }.map { |k, v| [k, v.size] }]
          @total_count = query_hash_stats.size
        end

        @tables = PgQuery.parse(@query).tables rescue []
        @tables.sort!

        if @tables.any?
          @row_counts = Hash[@database.table_stats(table: @tables).map { |i| [i[:table], i[:estimated_rows]] }]

app/helpers/pg_hero/base_helper.rb
module PgHero
  module BaseHelper
    def pghero_pretty_ident(table, schema: nil)
      ident = table
      if schema && schema != "public"
        ident = "#{schema}.#{table}"
      end
      if ident =~ /\A[a-z0-9_]+\z/
        ident
      else
        @database.quote_ident(ident)
      end
    end
  end
end

app/views/pg_hero/home/_connections_table.html.erb
<table class="table">
  <thead>
    <tr>
      <th>Top Sources</th>
      <th style="width: 20%;">Connections</th>
    </tr>
  </thead>
  <tbody>
    <% connection_sources.each do |source| %>
      <tr>
        <td><%= source[:source] %> <div class="text-muted"><%= [source[:user], source[:database], source[:ip]].compact.join(" - ") %></div></td>
        <td><%= number_with_delimiter(source[:total_connections]) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pg_hero/home/_queries_table.html.erb
<table class="table queries-table">
  <% unless local_assigns[:xhr] %>
    <thead>
      <tr>
        <th style="width: 33.33%;"><%= local_assigns[:sort_headers] ? link_to("Total Time", {sort: nil}, data: {sort: nil}) : "Total Time" %></th>
        <th style="width: 33.33%;"><%= local_assigns[:sort_headers] ? link_to("Average Time", {sort: "average_time"}, data: {sort: "average_time"}) : "Average Time" %></th>
        <th style="width: 33.33%;"><%= local_assigns[:sort_headers] ? link_to("Calls", {sort: "calls"}, data: {sort: "calls"}) : "Calls" %></th>
      </tr>
    </thead>
  <% end %>
  <tbody id="queries">
    <% if queries.empty? %>
      <tr>
        <td colspan="3">
          <p class="queries-info text-muted">
            <% if local_assigns[:xhr] %>
              No data available for this time.
            <% else %>
              ...
            <% end %>
          </p>
        </td>
      </tr>
    <% end %>
    <% queries.each do |query| %>
      <tr>
        <td>
          <%= number_with_delimiter(query[:total_minutes].round) %> min
          <span class="percent">
            <% percent = query[:total_percent] %>
            <% if percent > 1 %>
              <%= percent.round %>%
            <% elsif percent > 0.1 %>
              <%= percent.round(1) %>%
            <% else %>
              &lt; 0.1%
            <% end %>
          </span>
        </td>
        <td>
          <%= number_with_delimiter(query[:average_time].round) %> ms
        </td>
        <td>
          <%= number_with_delimiter(query[:calls]) %>

          <span class="user">
            <% if query[:user] %>
              <%= query[:user] %>
              <% if @show_details %>
                &middot;
              <% end %>
            <% end %>
            <% if @show_details && query[:query_hash] %>
              <%= link_to "details", show_query_path(query[:query_hash], user: query[:user]), target: "_blank" %>
            <% end %>
          </span>
        </td>
      </tr>
      <tr>
        <td colspan="3" style="border-top: none; padding: 0;">
          <pre><code style="max-height: 230px; overflow: hidden;" onclick="this.style.maxHeight = 'none';"><%= query[:query] %></code></pre>
          <% if query[:query] == "<insufficient privilege>" %>
            <p class="text-muted">For security reasons, only superusers can see queries executed by other users.</p>
          <% end %>
          <% if local_assigns[:suggested_indexes] != false && (details = @suggested_indexes_by_query[query[:query]]) && (details[:index] || @debug) %>
            <%= render partial: "suggested_index", locals: {index: details[:index], details: details} %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/pg_hero/home/_query_stats_slider.html.erb
<div id="slider-container">
  <div id="slider"></div>
  <div id="range-end"></div>
  <div id="range-start"></div>
</div>

<script>
  var sort = <%= @sort.to_json.html_safe %>;
  var minAverageTime = <%= @min_average_time.to_json %>;
  var minCalls = <%= @min_calls.to_json %>;
  var debug = <%= @debug.to_json %>;
  var startAt = <%= params[:start_at] ? @start_at.to_i * 1000 : "null" %>;
  var endAt = <%= @end_at.to_i %> * 1000;

  initSlider();
</script>

app/views/pg_hero/home/_suggested_index.html.erb
<% if index && !details[:covering_index] %>
  <% unless @debug %>
    <div style="float: right; color: #f0ad4e; margin-top: 0px; padding: 10px; cursor: pointer;" onclick="document.getElementById('details-<%= index.object_id %>').style.display = 'block'; this.style.display = 'none';">Details</div>
  <% end %>
  <code><pre style="color: #eee; background-color: #333;">CREATE INDEX CONCURRENTLY ON <%= index[:table] %><% if index[:using] %> USING <%= index[:using] %><% end %> (<%= index[:columns].join(", ") %>)</pre></code>
<% end %>
<div id="details-<%= index.object_id %>" style="<%= "display: none;" unless @debug %>">
  <code><pre style="color: #f0ad4e; background-color: #333;"><% if details[:explanation] %><%= details[:explanation] %>
<% end %><% if details[:row_estimates] %>Rows: <%= details[:rows] %>
Row progression: <%= details[:row_progression].to_a.join(", ") %>

Row estimates
<%= details[:row_estimates].to_a.map { |k, v| "- #{k}: #{v}" }.join("\n") %><% end %><% if details[:table_indexes] %>

Existing indexes
<% details[:table_indexes].sort_by { |i| [i[:primary] ? 0 : 1, i[:columns]] }.each do |i3| %>- <%= i3[:columns].join(", ") %><% if i3[:using] != "btree" %> <%= i3[:using].to_s.upcase %><% end %><% if i3[:primary] %> PRIMARY<% elsif i3[:unique] %> UNIQUE<% end %>
<% end %><% end %></pre></code>
</div>

app/views/pg_hero/home/landlord.html.erb
<div class="content">
  <h1>Landlord</h1>
  <% if !@query_stats_enabled %>
    <% if @query_stats_available && !@query_stats_extension_enabled %>
      <p>
        Query stats need to be enabled for Landlord a.k.a citus_stat_statements. They are available but not enabled.
        <%= button_to "Enable", enable_query_stats_path, class: "btn btn-info" %>
      </p>
    <% else %>
      <p>Query stats need to be enabled for Landlord a.k.a citus_stat_statements. Make them available by adding the following lines to <code>postgresql.conf</code>:</p>
      <pre>shared_preload_libraries = 'pg_stat_statements'
pg_stat_statements.track = all</pre>
      <p>Restart the server for the changes to take effect.</p>
    <% end %>
  <% else %>
    <% if !@landlord_available %>
      <p> 
        Landlord a.k.a <code>citus_stat_statements</code> view is a part of Citus Enterprise, starting from version 7.5. If you are already on Citus Enterprise, please 
        <a href = "https://docs.citusdata.com/en/latest/admin_guide/upgrading_citus.html"> upgrade Citus version</a>. Otherwise, please 
        <a href = "https://www.citusdata.com/about/contact_us">contact <b><span style="color: #239f49;">Citus</span> <span style="color: #09436a;">Data</span></b></a> 
        to obtain this functionality.
      </p>
    <% else %>
      <p> 
        Landlord a.k.a <code>citus_stat_statements</code> is a view that provides executor type, partition key value, and number of calls to a <b>distributed query</b>.
      </p>
      <% if @landlord_stats.any? %>
        <h3>Citus Executor Used</h3>
  
        <div id="chart-1" class="chart" style="height: 260px; line-height: 260px; margin-bottom: 20px;">Loading...</div>
        <script>
          new Chartkick.PieChart("chart-1", <%= json_escape(@grouped_dist_queries_executor.to_json).html_safe %>);
        </script>
        <% if @grouped_dist_queries_executor.to_h.key?("router") %>
          <% if @grouped_dist_queries_executor.to_h["router"] > @grouped_dist_queries_executor.sum{ |k, v| v } / 2 %>
            <p>
              More than half of the distributed queries use the <b>router</b> executor. This chart shows up to 20 busiest tenants.
            </p>
            <div id="chart-2" class="chart" style="height: 380px; line-height: 380px; width: 600px; margin-bottom: 20px; margin-left: auto; margin-right: auto;">Loading...</div>
            <script>
              new Chartkick.BarChart("chart-2", <%= json_escape(@grouped_dist_queries_partkey.to_json).html_safe %>, {colors: ["#5bc0de"], xtitle: ["#Queries"], ytitle: ["Tenant ID"]});
            </script>
          <% end %>
        <% end %>
        <h3>Distributed Query Stats Table</h3>
        <table class="table queries-table">
          <thead>
            <tr>
              <th><%= link_to "Executor", {sort: "executor"} %></th>
              <th><%= link_to "Partition Key", {sort: "partition_key"} %></th>
              <th><%= link_to "Calls", {} %></th>
            </tr>
          </thead>
          <tbody>
            <% @landlord_stats.each do |dist_query| %>
              <tr>
                <td>
                  <%= dist_query[:executor] %>
                </td>
                <td>
                  <%= dist_query[:partition_key] %>
                </td>
                <td>
                  <%= number_with_delimiter(dist_query[:calls]) %>
                </td>
              </tr>
              <tr>
                <td colspan="3" style="border-top: none; padding: 0;">
                  <pre><code style="max-height: 230px; overflow: hidden;" onclick="this.style.maxHeight = 'none';"><%= dist_query[:query] %></code></pre>
                  <% if dist_query[:query] == "<insufficient privilege>" %>
                    <p class="text-muted">For security reasons, only superusers can see queries executed by other users.</p>
                  <% end %>
                </td>
              </tr>
            <% end %>
          </tbody>
        </table>
        <script>
          highlightQueries();
        </script>
      <% else %>
        <p>No data available for this time.</p>
      <% end %>
    <% end %>
  <% end %>
</div>

app/views/pg_hero/home/live_queries.html.erb
<div class="content">
  <h1>Live Queries</h1>

  <p><%= pluralize(@running_queries.size, "query") %></p>

  <%= render partial: "live_queries_table", locals: {queries: @running_queries, vacuum_progress: @vacuum_progress} %>

  <p><%= button_to "Kill all connections", kill_all_path, class: "btn btn-danger" %></p>

  <p class="text-muted">You may need to restart your app server afterwards.</p>
</div>

app/views/pg_hero/home/queries.html.erb
<div class="content">
  <% if @query_stats_enabled %>
    <%= button_to "Reset", reset_query_stats_path, class: "btn btn-danger", style: "float: right;" %>
  <% end %>

  <h1 style="float: left;">Queries</h1>

  <% if @historical_query_stats_enabled %>
    <%= render partial: "query_stats_slider" %>
  <% elsif @database.query_stats_table_exists? && (columns = @database.missing_query_stats_columns).any? %>
    <div style="clear: both;">
      <p>Add missing columns to re-enable historical query stats.</p>
      <pre><code><% @database.missing_query_stats_columns.each do |column| %>ALTER TABLE pghero_query_stats ADD COLUMN "<%= column %>" <%= column == "query_hash" ? "bigint" : "text" %>;
<% end %></code></pre>
      <p>Then restart the web server.</p>
    </div>
  <% end %>

  <% if @query_stats_enabled %>
    <% if @error %>
      <div class="alert alert-danger">Cannot understand start or end time.</div>
    <% elsif @query_stats.any? || @historical_query_stats_enabled %>
      <%= render partial: "queries_table", locals: {queries: @query_stats, sort_headers: true} %>
      <script>
        highlightQueries();
      </script>
    <% else %>
      <p>Stats are not available yet. Come back soon!</p>
    <% end %>
  <% else %>
    <p>Query stats are not enabled.</p>
  <% end %>
</div>

app/views/pg_hero/home/space.html.erb
<div class="content">
  <h1>Space</h1>

  <p>Total Database Size: <%= @database_size %></p>
  <% if @citus_enabled %>
    <% @node_sizes.each do |node| %>
      <p><%= node[:name] %> Size: <%= PgHero.pretty_size(node[:size]) %></p>
    <% end %>
    <br>
  <% end %>

  <% if @system_stats_enabled %>
    <div id="chart-1" class="chart" style="margin-bottom: 20px;">Loading...</div>
    <script>
      new Chartkick.LineChart("chart-1", <%= json_escape(free_space_stats_path.to_json).html_safe %>, {colors: ["#5bc0de"]})
    </script>
  <% end %>

  <!--
  <% if @index_bloat.any? %>
    <p>Check out <%= link_to "index bloat", index_bloat_path %> for an easy way to reclaim space.</p>
  <% end %>
  -->

  <% if @unused_indexes.any? %>
    <p>
      <%= pluralize(@unused_indexes.size, "unused index") %>. Remove them
      <% if @show_migrations %>
        <a href="javascript: void(0);" onclick="document.getElementById('migration').style.display = 'block';">with a migration</a>
      <% end %>
      for faster writes.

      <% if @database.replicating? %>
        Check they aren’t used on replicas.
      <% end %>
    </p>

    <div id="migration" style="display: none;">
      <pre>rails g migration remove_unused_indexes</pre>
      <p>And paste</p>
      <pre style="overflow: scroll; white-space: pre; word-break: normal;"><% @unused_indexes.sort_by { |q| [-q[:size_bytes], q[:index]] }.each do |query| %>
remove_index <%= query[:table].to_sym.inspect %>, name: <%= query[:index].to_s.inspect %><% end %></pre>
    </div>
  <% end %>

  <table class="table space-table">
    <thead>
      <tr>
        <th><%= link_to "Relation", {sort: "name"} %></th>
        <th style="width: 15%;"><%= link_to "Size", {} %></th>
        <% if @space_stats_enabled %>
          <th style="width: 15%;"><%= link_to "#{@days}d Growth", {sort: "growth"} %></th>
        <% end %>
      </tr>
    </thead>
    <tbody>
      <% @relation_sizes.each do |query| %>
        <tr>
          <td style="<%= query[:type] == "index" ? "font-style: italic;" : "" %>">
            <span style="word-break: break-all;">
              <% name = query[:relation] || query[:table] %>
              <% if @space_stats_enabled %>
                <%= link_to name, relation_space_path(name, schema: query[:schema]), target: "_blank", style: "color: inherit;" %>
              <% else %>
                <%= name %>
              <% end %>
            </span>
            <% if query[:schema] != "public" %>
              <span class="text-muted"><%= query[:schema] %></span>
            <% end %>
            <% if query[:partmethod] != "-" %>
              <span style="color: #239f49;"><em> <%= query[:partmethod] %> </em></span>
            <% end %>
            <% if @unused_index_names.include?(query[:relation]) %>
              <span class="unused-index">UNUSED</span>
            <% end %>
          </td>
          <td><%= query[:size] %></td>
          <% if @space_stats_enabled %>
            <td>
              <% if @growth_bytes_by_relation[[query[:schema], query[:relation]]] %>
                <% if @growth_bytes_by_relation[[query[:schema], query[:relation]]] < 0 %>-<% end %><%= PgHero.pretty_size(@growth_bytes_by_relation[[query[:schema], query[:relation]]].abs) %>
              <% else %>
                <span class="text-muted">Unknown</span>
              <% end %>
            </td>
          <% end %>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/pg_hero/home/system.html.erb
<div class="content">
  <p id="periods">
    <% @periods.each do |name, options| %>
      <%= link_to name, system_path(options) %>
    <% end %>
  </p>
  <% path_options = {duration: @duration, period: @period} %>

  <h1>CPU</h1>
  <div id="chart-1" class="chart" style="margin-bottom: 20px;">Loading...</div>
  <script>
    new Chartkick.LineChart("chart-1", <%= json_escape(cpu_usage_path(path_options).to_json).html_safe %>, {max: 100, colors: ["#5bc0de"]})
  </script>

  <h1>Load</h1>
  <div id="chart-2" class="chart" style="margin-bottom: 20px;">Loading...</div>
  <script>
    new Chartkick.LineChart("chart-2", <%= json_escape(load_stats_path(path_options).to_json).html_safe %>, {colors: ["#5bc0de", "#d9534f"]})
  </script>

  <h1>Connections</h1>
  <div id="chart-3" class="chart" style="margin-bottom: 20px;">Loading...</div>
  <script>
    new Chartkick.LineChart("chart-3", <%= json_escape(connection_stats_path(path_options).to_json).html_safe %>, {colors: ["#5bc0de"]})
  </script>

  <% if @database.replica? %>
    <h1>Replication Lag</h1>
    <div id="chart-4" class="chart" style="margin-bottom: 20px;">Loading...</div>
    <script>
      new Chartkick.LineChart("chart-4", <%= json_escape(replication_lag_stats_path(path_options).to_json).html_safe %>, {colors: ["#5bc0de"]})
    </script>
  <% end %>
</div>